@url = http://localhost:4182

GET {{url}}/api/v1/product HTTP/1.1
content-type: application/json

{
}

###

POST {{url}}/api/v1/product/like/60e92973c7a7423561aa7b84 HTTP/1.1
content-type: application/json

{
  "like": true
}

###

GET {{url}}/api/v1/employee HTTP/1.1
content-type: application/json

{
}
