version: "3.8"

services:
  pgserver:
    build:
      context: ./server
      dockerfile: docker/Dockerfile
    depends_on:
      - mongo
    networks:
      - internal
    ports:
      - 4172:4172
    environment:
      PORT: 4172
      MODE: production
      MONGO_URL: mongo:27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: playground

  pgclient:
    build:
      context: ./client
      dockerfile: docker/Dockerfile
    depends_on:
      - pgserver
    networks:
      - internal
    ports:
      - 4171:80

  mongo:
    image: mongo:4-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: playground
    volumes:
      - mongo-volume:/data/db
      - ./scripts:/scripts
    networks:
      - internal
    ports:
      - 26521:27017

  mongo-express:
    image: mongo-express:0.54
    depends_on:
      - mongo
    restart: always
    networks:
      - internal
    ports:
      - 8092:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: playground
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: playground

networks:
  internal:
    driver: bridge

volumes:
  mongo-volume:
    driver: local
